# Site settings
title: Asphodeli
email: ''
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: '/deli_landed/'
url: ''

# Social media
twitter_username: #uclatommy
github_username:  crossfitasphodel

# Template Text
menu_topright_title: '' #'Asphodeli'
logo_url: '/images/logo_white.png'
copyright: '<i class="fa fa-map-marker"></i> 22 Praya, Kennedy Town <i class="fa fa-mobile"></i> +852 2467 1838 <i class="fa fa-envelope-o"></i> deli@crossfitasphodel.com' #'&copy; Made by Asphodel. All rights reserved.'
designby: '<a href="">Tom Panerai</a> Photo: <a href="">Peter Pan</a> Web: <a href="http://instagram.com/johnho.ca/">JHO</a>'

# Build settings
markdown: kramdown
