# Site settings
title: Asphodeli
email: ''
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: #'/deli/'
url: ''
google_analytics_tracking_id: 'UA-113151610-2' # under john@keepmovingproject.org

# Social media -- NOT USED: see site.data.nav --
twitter_username: #uclatommy
github_username:  crossfitasphodel

# Template Text
menu_sticky: False
menu_topright_title: '' #'Asphodeli'
logo_url: '/images/logo_white.png'
copyright: '<a href="https://goo.gl/maps/34suTJsRJfy" target="_blank"><i class="fa fa-map-marker"></i> 22 Praya, Kennedy Town</a> &#9702; <i class="fa fa-mobile"></i> +852 2467 1838 <a href="emailto:deli@crossfitasphodel.com"> &#9702; <i class="fa fa-envelope-o"></i> deli@crossfitasphodel.com</a>' #'&copy; Made by Asphodel. All rights reserved.'
designby: '<a href="https://www.instagram.com/onetomphoto/" target="_blank">ONETOM</a> &#9702; Photo: <a href="https://www.instagram.com/pape_photo/" target="_blank">PAPE_PHOTO</a> &#9702; Web: <a href="http://instagram.com/johnho.ca/" target="_blank">JHO</a>'

# Build settings
markdown: kramdown
